<?php

echo urlencode("<p>In the sentence:&#160;<strong><em>\"</em></strong>
{{sentence}}<strong><em>\"</em></strong></p>
<p>Is<strong>&#160;</strong>
{{term1}}<strong>&#160;</strong>&#160;<em><strong>----</strong>related-to<strong>----&#160;</strong></em>&#160;
{{term2}}?</p>
<p><strong></strong></p>
<cml:checkboxes label=\"Select the valid RELATION(s)\" class=\"\" instructions=\"It is important that you understand what the different relation types mean. Definitions and examples are given in each choice\" validates=\"required\"><cml:checkbox label=\"[TREATS]: therapeutic use of an ingredient or a drug, e.g. penicillin cures infection, etc.\" value=\"[TREATS]\"/><cml:checkbox label=\"[PREVENTS]: preventative use of an ingredient or a drug, e.g. vitamin C reduces the risk of influenza, etc.\" value=\"[PREVENTS]\"/><cml:checkbox label=\"[DIAGNOSED_BY_TEST_OR_DRUG]: diagnostic use of an ingredient, test or a drug, e.g.  RINNE test is used for determining hearing loss, etc.\" value=\"[DIAGNOSED_BY_TEST_OR_DRUG]\"/><cml:checkbox label=\"[CAUSES]: the underlying reason for a symptom or a disease, e.g. fever induces dizziness etc.\" value=\"[CAUSES]\"/><cml:checkbox label=\"[LOCATION]: body part or anatomical structure in which disease or disorder is observed, e.g. leukimia is found in the circulatory system, etc.\" value=\"[LOCATION]\"/><cml:checkbox label=\"[SYMPTOM]: deviation from normal function indicating the presence of disease or abnormality, e.g. pain is a symptom of a broken arm, etc.\" value=\"[SYMPTOM]\"/><cml:checkbox label=\"[MANIFESTATION]: links disorders to the observations (manifestations) that are closely associated with them, e.g. abdominal distension is a manifestation of liver failure\" value=\"[MANIFESTATION]\" id=\"\"/><cml:checkbox label=\"[CONTRAINDICATES]: a condition that indicates that drug or treatment SHOULD NOT BE USED, e.g. patients with obesity should avoid using danazol\" value=\"[CONTRAINDICATES]\"/><cml:checkbox label=\"[ASSOCIATED_WITH]: signs, symptoms or findings that often appear together, e.g. patients who smoke often have yellow teeth.\" value=\"[ASSOCIATED_WITH]\"/><cml:checkbox label=\"[SIDE_EFFECT]: a secondary condition or symptom that results from a drug or treatment, e.g. use of antidepressants causes dryness in the eyes.\" value=\"[SIDE_EFFECT]\"/><cml:checkbox label=\"[IS_A]: a relation that indicates that one of the terms is more specific variation of the other, e.g. migraine is a kind of headache. \" value=\"[IS_A]\"/><cml:checkbox label=\"[PART_OF]: an anatomical or structural sub-component, e.g. the left ventrical is part of the heart\" value=\"[PART_OF]\"/><cml:checkbox label=\"[OTHER]: the words are related, but not by any of the above relations\" value=\"[OTHER]\"/><cml:checkbox label=\"[NONE]: there is no relation between those words in this sentence\" value=\"[NONE]\"/></cml:checkboxes>");

?>
